//! dotenvx backend decryption (plan 132 phase 4, decision D2).
//!
//! Decrypts `KEY="encrypted:BASE64..."` values from a dotenvx-encrypted
//! `.env` file. Wire format (eciesjs defaults, verified against the
//! reference `@dotenvx/dotenvx` CLI):
//!
//! ```text
//! blob      = ephemeral_pub(65, uncompressed SEC1)
//!             || nonce(16) || tag(16) || ciphertext
//! ecdh      = (ephemeral_pub × receiver_scalar) as uncompressed SEC1 (65)
//! key       = HKDF-SHA256(ikm = ephemeral_pub(65) || ecdh(65),
//!                         salt = ∅, info = ∅, out = 32)
//! plaintext = AES-256-GCM(key, nonce16).decrypt(ciphertext, tag)
//! ```
//!
//! Deps are pure-Rust RustCrypto crates (`k256`, `aes-gcm`, `hkdf`),
//! consistent with the existing `rsa`/`sha2`/`hmac` choices — no C
//! toolchain. All errors are value-free by construction (they can only
//! name keys and structural problems, never decrypted bytes).

use aes_gcm::aead::consts::U16;
use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::aes::Aes256;
use aes_gcm::AesGcm;
use base64::engine::general_purpose::STANDARD;
use base64::Engine;
use hkdf::Hkdf;
use k256::elliptic_curve::sec1::ToEncodedPoint;
use k256::{ProjectivePoint, PublicKey, SecretKey};
use sha2::Sha256;

/// AES-256-GCM with eciesjs's 16-byte nonce (not the GCM-standard 12).
type Aes256Gcm16 = AesGcm<Aes256, U16>;

const EPHEMERAL_KEY_SIZE: usize = 65;
const NONCE_SIZE: usize = 16;
const TAG_SIZE: usize = 16;
pub(crate) const ENCRYPTED_PREFIX: &str = "encrypted:";

fn decode_hex(s: &str) -> Result<Vec<u8>, String> {
    let s = s.trim();
    if s.len() % 2 != 0 {
        return Err("private key hex has odd length".to_string());
    }
    (0..s.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(&s[i..i + 2], 16)
                .map_err(|_| "private key is not valid hex".to_string())
        })
        .collect()
}

/// Decrypt one `encrypted:` value with a hex-encoded secp256k1 private
/// key. The error never contains plaintext or key material.
pub(crate) fn decrypt_value(private_key_hex: &str, value: &str) -> Result<String, String> {
    let payload = value
        .strip_prefix(ENCRYPTED_PREFIX)
        .ok_or_else(|| "value does not start with 'encrypted:'".to_string())?;
    let blob = STANDARD
        .decode(payload.trim())
        .map_err(|_| "encrypted payload is not valid base64".to_string())?;
    if blob.len() < EPHEMERAL_KEY_SIZE + NONCE_SIZE + TAG_SIZE {
        return Err("encrypted payload is too short".to_string());
    }
    let (ephemeral, rest) = blob.split_at(EPHEMERAL_KEY_SIZE);
    let (nonce, rest) = rest.split_at(NONCE_SIZE);
    let (tag, ciphertext) = rest.split_at(TAG_SIZE);

    let secret = SecretKey::from_slice(&decode_hex(private_key_hex)?)
        .map_err(|_| "invalid private key".to_string())?;
    let ephemeral_pub =
        PublicKey::from_sec1_bytes(ephemeral).map_err(|_| "bad ephemeral point".to_string())?;

    // ECDH with the FULL uncompressed point (eciesjs isHkdfKeyCompressed
    // = false), not just the x coordinate.
    let shared_point = (ProjectivePoint::from(*ephemeral_pub.as_affine())
        * *secret.to_nonzero_scalar())
    .to_affine()
    .to_encoded_point(false);

    let mut ikm = Vec::with_capacity(EPHEMERAL_KEY_SIZE * 2);
    ikm.extend_from_slice(ephemeral);
    ikm.extend_from_slice(shared_point.as_bytes());
    let mut key = [0u8; 32];
    Hkdf::<Sha256>::new(None, &ikm)
        .expand(&[], &mut key)
        .map_err(|_| "hkdf expand failed".to_string())?;

    // aes-gcm expects ciphertext || tag.
    let mut ct_tag = Vec::with_capacity(ciphertext.len() + TAG_SIZE);
    ct_tag.extend_from_slice(ciphertext);
    ct_tag.extend_from_slice(tag);
    let cipher =
        Aes256Gcm16::new_from_slice(&key).map_err(|_| "bad derived key".to_string())?;
    let plain = cipher
        .decrypt(nonce.into(), Payload { msg: &ct_tag, aad: &[] })
        .map_err(|_| "decryption failed (wrong private key or corrupted value)".to_string())?;
    String::from_utf8(plain).map_err(|_| "decrypted value is not UTF-8".to_string())
}

/// Try each comma-separated private key (dotenvx supports key rotation
/// by listing multiple), returning the first success.
pub(crate) fn decrypt_value_multi(private_keys: &str, value: &str) -> Result<String, String> {
    let mut last_err = "no private key provided".to_string();
    for key in private_keys.split(',').filter(|k| !k.trim().is_empty()) {
        match decrypt_value(key, value) {
            Ok(plain) => return Ok(plain),
            Err(e) => last_err = e,
        }
    }
    Err(last_err)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Reference fixture generated by the dotenvx CLI (`npx
    // @dotenvx/dotenvx encrypt`, v1.x) — wire-format compatibility pin.
    // The keypair exists only for this test.
    const PRIVATE_KEY: &str = "3814d8f08ca805a0d64be3d91b16bf0d86a6d6e5bd96071ebf92a45703f76e55";
    const TOKEN_BLOB: &str = "encrypted:BAwSPG1rQrOjqubSmWpBEElpWopKcEVnyZsRfTNvrO8IAhtRRBeFJN2h3NyKTlNDDS5b/Pjn+sMiMlrQbeJL4r7mVDJjHFSULmGskr4YQKUaVKAGAVWc6o9mv8meA59tP5cwFxaV3j0iMx+tj7vVei/ajcVIQFM=";
    const SECOND_BLOB: &str = "encrypted:BJEhABQwIV6NJ7dEcEQWmBq492yX+KSuqxClySRug7X4GEDyi6TBYX9Yp3wos4IQWhJ4PCTIrXZm7j/mzjZzb+MX7iKqyziBZNpJ+Qgj1gjBlvXL2ivq6FtF9e4RDrxjm0LAJzmX3T+cXaRJ1FUuzkA+ZDganswJNQ==";

    #[test]
    fn decrypts_reference_dotenvx_values() {
        assert_eq!(
            decrypt_value(PRIVATE_KEY, TOKEN_BLOB).unwrap(),
            "fixture-secret-hunter2"
        );
        assert_eq!(
            decrypt_value(PRIVATE_KEY, SECOND_BLOB).unwrap(),
            "second value with spaces"
        );
    }

    #[test]
    fn wrong_key_fails_without_leaking() {
        let wrong = "0000000000000000000000000000000000000000000000000000000000000001";
        let err = decrypt_value(wrong, TOKEN_BLOB).unwrap_err();
        assert!(!err.contains("hunter2"), "error must not leak plaintext");
    }

    #[test]
    fn multi_key_rotation_tries_each() {
        let ring = format!(
            "0000000000000000000000000000000000000000000000000000000000000001,{}",
            PRIVATE_KEY
        );
        assert_eq!(
            decrypt_value_multi(&ring, TOKEN_BLOB).unwrap(),
            "fixture-secret-hunter2"
        );
    }

    #[test]
    fn malformed_inputs_are_clean_errors() {
        assert!(decrypt_value(PRIVATE_KEY, "not-encrypted").is_err());
        assert!(decrypt_value(PRIVATE_KEY, "encrypted:!!!").is_err());
        assert!(decrypt_value(PRIVATE_KEY, "encrypted:AAAA").is_err());
        assert!(decrypt_value("zz", TOKEN_BLOB).is_err());
    }
}
