[package]
name = "fai-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "fai_cli"
path = "src/lib.rs"

[[bin]]
name = "forai"
path = "src/main.rs"

[[bin]]
name = "fai"
path = "src/fai.rs"

[dependencies]
fai-core = { path = "../fai-core" }
fai-checker = { path = "../fai-checker" }
fai-compiler = { path = "../fai-compiler" }
fai-parser = { path = "../fai-parser" }
fai-codegen-wasm = { path = "../fai-codegen-wasm" }
fai-ffi = { path = "../fai-ffi" }
wasmtime = "29"
wasmparser = "0.221"
sha2 = { version = "0.10", features = ["oid"] }
sha1 = "0.10"
hmac = "0.12"
getrandom = "0.2"
base64 = "0.21"
subtle = "2"
rsa = "0.9"
ureq = { workspace = true, optional = true }
mio = { workspace = true }
flate2 = { workspace = true, optional = true }
tar = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
jmespath = "0.5"
k256 = "0.13.4"
aes-gcm = "0.10"
hkdf = "0.12"

[features]
default = ["http-client"]
http-client = ["ureq", "flate2", "tar"]
